name: Release Plugin

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  release-plugin-to-jetbrains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Add execution privileges
        run: chmod +x ./gradlew
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          CERTIFICATE_CHAIN: op://Hosting-Secrets/JetBrains-Marketplace-Signing-Certificate/add more/Certificate-String
          PRIVATE_KEY: op://Hosting-Secrets/JetBrains-Marketplace-Signing-Certificate/add more/RSA-Private-Key
          PRIVATE_KEY_PASSWORD: op://Hosting-Secrets/JetBrains-Marketplace-Signing-Certificate/add more/Certificate-Password
          PUBLISH_TOKEN: op://Hosting-Secrets/signed-todos-marketplace-token/credential
      - name: Sign and release Plugin
        runs: ./gradlew signPlugin
#  create-github-release:
